# Generated by Django 3.2 on 2022-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('csv_file', models.FileField(upload_to='csv')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
